# Dependencies
gems:             [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Adalbert FX Wilhelm
tagline:          'BLOGS'
description:      Statistics@Jacobs University
url:              http://www.jacobs-university.de/awilhelm
baseurl:          /

author:
  name:           'Adalbert FX Wilhelm'
  url:            http://www.jacobs-university.de/awilhelm

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/afxwilhelm

google_analytics: UA-55002898-4
